services:
  reg-app:
    build: .
    ports:
      - "4152"
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      DB_HOST: db
  load-balancer:
    build: ./load_balancer/
    ports:
      - "7993:7993"
    depends_on:
      - reg-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: mysql:8.0
    volumes:
      - ./database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER} 
      MYSQL_PASSWORD: ${DB_PW}
